### ISSUE TITLE
Перевод magiceffects.json

### ISSUE THREAD

**Issue by Lime18** [Ou1Law/Translation-into-Russian-mod-EpicLoot-for-Valheim#1]
Привет, спасибо большое за перевод EpicLoot, добавь пожалуйста перевод для magiceffects.json

**Comment by Ou1Law** [comment]
magiceffects.json не требует перевода так как названия все магических эффектов теперь внесены в основной файл перевода

**Comment by Ou1Law** [comment]
Начиная с версии мода 0.7.8 описание всех магических эффектов перенесены в основной файл перевода
Перевод и ReadMe был обновлен настоятельно рекомендую ознакомиться

**Comment by Lime18** [comment]
Благодарю за разъяснение.
