### ISSUE TITLE
Отличный перевод.

### ISSUE THREAD

**Issue by papay88** [Ou1Law/Translation-into-Russian-mod-EpicLoot-for-Valheim#2]
Спасибо тебе за твою работу, я пытаюсь развить ру сообщество по игре и надеюсь ты не будет против того, что я выложил твой перевод на своем [сайте ](https://valheimod.ru/index.php?resources/epic-loot-rus.17/)

**Comment by Ou1Law** [comment]
Конечно пользуй наздоровье, рад что кому то пригодилось.

**Comment by papay88** [comment]
Спасибо, это пригодиться всему русскому сообществу, так как это самый популярный плагин на данный момент по запросам и очень много людей ищут перевод плагина. Если будет интересно, буду рад видеть тебя на форуме, дискорде или в вк моего проекта, могу сделать отдельные темы для обсуждения твоего перевода и фидбека.

**Comment by Ou1Law** [comment]
Набросал тебе список обалденных модов можешь к себе на сайт присовокупить
Это всяческие фиксы или моды для удобства

https://www.nexusmods.com/valheim/mods/1202       Unstripped DLLs for BepInEx 5.4.1001

https://www.nexusmods.com/valheim/mods/205     Simple Recycling - разборка предметов дополняет EpicLoot 

https://www.nexusmods.com/valheim/mods/441     Trash Items - отлично встроенная в HUD настраиваемая корзина

https://www.nexusmods.com/valheim/mods/241      Floating Items -настройка предметов которые плавают(чешуя змея и трофей змея можно добавить к примеру)

https://www.nexusmods.com/valheim/mods/121       Use Equipment in Water -возм использовать предметы в воде

https://www.nexusmods.com/valheim/mods/335       Pickable Time Fix -жутко полезный фикс времени сбора с кустов
https://www.nexusmods.com/valheim/mods/1042     PlantEverething   -лучший из доступных(Rus) выращивай что угодно

https://www.nexusmods.com/valheim/mods/284       Plant Grow Progress   показ в % сколько осталось до урожая
https://www.nexusmods.com/valheim/mods/825       Fermenter Utilities      показ в % сколько осталось до бухла

https://www.nexusmods.com/valheim/mods/1078      My Favorite Hoe -удобно сделанная многофункциональная мотыга
https://www.nexusmods.com/valheim/mods/1113      Terrain Reset       -восстанавливает стандарт ландшафт с зажатым ALT

https://www.nexusmods.com/valheim/mods/65           Gravekeeper    - увеличивает размер надгробия
https://www.nexusmods.com/valheim/mods/103         More Slots       - без багов если использовать без колчана BetterArchery
Эти 2 мода работают в паре конфликтуют с EQ&QS 

https://www.nexusmods.com/valheim/mods/1013       ValheimFPSBoost2 - отличный мод отключает тени

**Comment by Ou1Law** [comment]
Да было бы не плохо чтобы люди могли оставлять отзывы о переводе, ошибки и тд, тесты занимают кучу времени(рандом убивает)

**Comment by papay88** [comment]
1. Насчет плагинов спасибо, добавлю их. Сейчас понял, что нужно на сайте поменять структуру раздела плагины, изначально не верный вариант выбрал.
2. В эти выходные или на след.недели создам отдельную тему о твоем переводе, с описанием, возможностью отдельно скачать, приемом ошибок. В дискорде могу создать отдельную ветку с каналами обсуждения перевода и сбором ошибок.
3. Пока особо раскруткой проекта не занимался, много сил уходит на его полировку, так как тоже один всем занимаюсь.

**Comment by Ou1Law** [comment]
О да полировка она самая сложная) я тебя понимаю время затраченное на перевод - 30-60 минут допилка идет днями,
на счет дискорда отдельная ветка это хорошо (кстати дай ссылку) а вот на сайте перевод лучше оставить вместе с плагином в текущей форме. Если же ты разделишь плагины на категории, и в описании каждого добавишь зависимости и требования как на нексусе например то да, можно и отдельную страничку.

**Comment by Ou1Law** [comment]
Нашел дискорд могу дать пару советов по поводу оформления(кнопки ВК и дискорд сделать больше раза в 2, подписать, и сделать белыми а не серыми а то они так органично вписались в заставку что не видно)
вкладку "Ресурсы" переименовать в "Модификации" и поставить её на второе место (слева направо) туда заглядывают чаще чем в что нового

**Comment by papay88** [comment]
> Если же ты разделишь плагины на категории, и в описании каждого добавишь зависимости и требования как на нексусе например то да, можно и отдельную страничку.

Так и планировал сделать, как отдельный ресурс, а в него добавить ссылку обсуждение на форуме. Но перевод так же всегда будет добавлен как отдельный файл для закачки и в самом ресурсы эпик лут, как сейчас сделано.

> Нашел дискорд могу дать пару советов по поводу оформления(кнопки ВК и дискорд сделать больше раза в 2, подписать, и сделать белыми а не серыми а то они так органично вписались в заставку что не видно)
> вкладку "Ресурсы" переименовать в "Модификации" и поставить её на второе место (слева направо) туда заглядывают чаще чем в что нового

Понял, поправлю.
